// This is a skeleton starter React component generated by Plasmic.
// Feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicInput__VariantsArgs,
  PlasmicInput
} from "./plasmic/copy_of_cloudflare_ip_checker/PlasmicInput"; // plasmic-import: RGeap8xl0N4/render

interface InputProps extends React.ComponentProps<"input"> {
  // className prop is required for positioning instances of
  // this Component
  className?: string;
  children?: never;
}

function Input(props: InputProps) {
  const [focusWithin, setFocusWithin] = React.useState(false);
  const { className, ...inputProps } = props;
  return (
    <PlasmicInput
      variants={{
        focusWithin: focusWithin
      }}
      args={{
        placeholder: props.placeholder
      }}
      input={{
        ...inputProps,
        onBlur: () => setFocusWithin(false),
        onFocus: () => setFocusWithin(true)
      }}
      root={{
        className
      }}
    />
  );
}

export default Input as React.FunctionComponent<
  React.ComponentProps<typeof Input>
>;
