// This is a skeleton starter React component generated by Plasmic.
// Feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicMainPage__VariantsArgs,
  PlasmicMainPage
} from "./plasmic/copy_of_cloudflare_ip_checker/PlasmicMainPage"; // plasmic-import: IrI87iixQUu/render

interface MainPageProps {
  // className prop is required for positioning instances of
  // this Component
  className?: string;
  children?: never;
}

function MainPage(props: MainPageProps) {
  return (
    <PlasmicMainPage
      root={
        // className prop needs to be piped to the root element of this component
        { className: props.className }
      }
    />
  );
}

export default MainPage as React.FunctionComponent<
  React.ComponentProps<typeof MainPage>
>;
