// This is a skeleton starter React component generated by Plasmic.
// Feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicMainPage__VariantsArgs,
  PlasmicMainPage
} from "./plasmic/copy_of_cloudflare_ip_checker/PlasmicMainPage"; // plasmic-import: IrI87iixQUu/render
import isCloudflare from "@authentication/cloudflare-ip";

interface MainPageProps {
  className?: string;
}

function getStatus(value: string) {
  try {
    return isCloudflare(value) ? "valid" : "invalid";
  } catch (ex) {
    return undefined;
  }
}

function MainPage(props: MainPageProps) {
  const [value, setValue] = React.useState("");
  return (
    <PlasmicMainPage
      root={{
        className: props.className
      }}
      input={{
        value: value,
        onChange: (e) => setValue(e.target.value)
      }}
      validationResultIcon={{
        status: getStatus(value)
      }}
    />
  );
}

export default MainPage;
