// This is a skeleton starter React component generated by Plasmic.
// Feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicSpacer__VariantsArgs,
  PlasmicSpacer
} from "./plasmic/copy_of_cloudflare_ip_checker/PlasmicSpacer"; // plasmic-import: BrV3uEHn-Yj/render

interface SpacerProps {
  // className prop is required for positioning instances of
  // this Component
  className?: string;
  children?: never;
}

function Spacer(props: SpacerProps) {
  return (
    <PlasmicSpacer
      spacer={
        // className prop needs to be piped to the root element of this component
        { className: props.className }
      }
    />
  );
}

export default Spacer as React.FunctionComponent<
  React.ComponentProps<typeof Spacer>
>;
