/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsx createPlasmicElementProxy */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pVt2oR5EtQUEdy73p3KcxV
// Component: IB70_6M4C4N
import * as React from "react";
import {
  hasVariant,
  createPlasmicElement,
  RenderOpts,
  Override,
  classNames,
  Flex,
  wrapWithClassName,
  Renderer,
  NodeRenderer,
  createPlasmicElementProxy,
  makeFragment,
  PlasmicIcon,
  PlasmicSlot,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_copy_of_cloudflare_ip_checker.css"; // plasmic-import: pVt2oR5EtQUEdy73p3KcxV/projectcss
import "./PlasmicValidationResultIcon.css"; // plasmic-import: IB70_6M4C4N/css

export type PlasmicValidationResultIcon__VariantsArgs = {
  status?: SingleChoiceArg<"valid" | "invalid">;
};

export type PlasmicValidationResultIcon__ArgsType = {};

const PlasmicValidationResultIcon__RenderFuncs = {
  root: (
    opts: RenderOpts<
      PlasmicValidationResultIcon__VariantsArgs,
      PlasmicValidationResultIcon__ArgsType,
      {
        root?: Flex<"div">;
        box?: Flex<"div">;
      }
    >
  ): React.ReactElement => {
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};
    return (
      <div
        data-plasmic-override={overrides.root}
        className={classNames({
          "ValidationResultIcon__root--baseLg__8yK46pINBE_FGEW3": true,
          "ValidationResultIcon__root--invalid__8yK46vl0W7": hasVariant(
            variants,
            "status",
            "invalid"
          ),

          "ValidationResultIcon__root--valid__8yK46mA3uj": hasVariant(
            variants,
            "status",
            "valid"
          ),

          ValidationResultIcon__root__8yK46: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      >
        {PlasmicValidationResultIcon__RenderFuncs.box({
          variants,
          args,
          overrides
        })}
      </div>
    );
  },
  box: (
    opts: RenderOpts<
      PlasmicValidationResultIcon__VariantsArgs,
      PlasmicValidationResultIcon__ArgsType,
      {
        box?: Flex<"div">;
      }
    >
  ): React.ReactElement => {
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};
    return (
      <div
        data-plasmic-override={overrides.box}
        className={classNames({
          "ValidationResultIcon__box--baseLg__T6qhopINBE_FGEW3": true,
          "ValidationResultIcon__box--invalid__T6qhovl0W7": hasVariant(
            variants,
            "status",
            "invalid"
          ),

          "ValidationResultIcon__box--valid__T6qhomA3uj": hasVariant(
            variants,
            "status",
            "valid"
          ),

          ValidationResultIcon__box__T6qho: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      >
        {hasVariant(variants, "status", "invalid")
          ? "✗"
          : hasVariant(variants, "status", "valid")
          ? "✓"
          : "?"}
      </div>
    );
  }
};

const PlasmicValidationResultIcon__FCs = {
  root: undefined,
  box: undefined
};

class PlasmicValidationResultIcon__Renderer extends Renderer<
  PlasmicValidationResultIcon__VariantsArgs,
  PlasmicValidationResultIcon__ArgsType,
  typeof PlasmicValidationResultIcon__RenderFuncs,
  "root"
> {
  constructor(
    variants: PlasmicValidationResultIcon__VariantsArgs,
    args: PlasmicValidationResultIcon__ArgsType
  ) {
    super(variants, args, PlasmicValidationResultIcon__RenderFuncs, "root");
  }

  protected create(
    variants: PlasmicValidationResultIcon__VariantsArgs,
    args: PlasmicValidationResultIcon__ArgsType
  ) {
    return new PlasmicValidationResultIcon__Renderer(variants, args);
  }

  withVariants(
    variants: PlasmicValidationResultIcon__VariantsArgs
  ): PlasmicValidationResultIcon__Renderer {
    return super.withVariants(
      variants
    ) as PlasmicValidationResultIcon__Renderer;
  }

  withArgs(
    args: PlasmicValidationResultIcon__ArgsType
  ): PlasmicValidationResultIcon__Renderer {
    return super.withArgs(args) as PlasmicValidationResultIcon__Renderer;
  }

  getInternalVariantProps() {
    return ["status"];
  }

  getInternalArgProps() {
    return [];
  }

  forNode(
    name: "root"
  ): NodeRenderer<typeof PlasmicValidationResultIcon__RenderFuncs["root"]>;
  forNode(
    name: "box"
  ): NodeRenderer<typeof PlasmicValidationResultIcon__RenderFuncs["box"]>;
  forNode(name: keyof typeof PlasmicValidationResultIcon__RenderFuncs) {
    return super.forNode(name);
  }
}

interface PlasmicValidationResultIconRootProps {
  variants?: PlasmicValidationResultIcon__VariantsArgs;
  args?: Partial<PlasmicValidationResultIcon__ArgsType>;
  root?: Flex<"div">;
  box?: Flex<"div">;
}

export const PlasmicValidationResultIcon = ((
  props: PlasmicValidationResultIconRootProps
) => {
  return new PlasmicValidationResultIcon__Renderer(
    props.variants || {},
    props.args || {}
  )
    .forNode("root")
    .withOverrides({
      root: props.root,
      box: props.box
    })
    .render();
}) as React.FunctionComponent<PlasmicValidationResultIconRootProps> & {
  box: React.FunctionComponent<PlasmicValidationResultIconBoxProps>;
  createRenderer: () => PlasmicValidationResultIcon__Renderer;
};

interface PlasmicValidationResultIconBoxProps {
  variants?: PlasmicValidationResultIcon__VariantsArgs;
  args?: Partial<PlasmicValidationResultIcon__ArgsType>;
  box?: Flex<"div">;
}

PlasmicValidationResultIcon.box = ((
  props: PlasmicValidationResultIconBoxProps
) => {
  return new PlasmicValidationResultIcon__Renderer(
    props.variants || {},
    props.args || {}
  )
    .forNode("box")
    .withOverrides({
      box: props.box
    })
    .render();
}) as React.FunctionComponent<PlasmicValidationResultIconBoxProps>;

PlasmicValidationResultIcon.createRenderer = () =>
  new PlasmicValidationResultIcon__Renderer({}, {});

export default PlasmicValidationResultIcon;
/* prettier-ignore-end */
