/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsx createPlasmicElementProxy */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pVt2oR5EtQUEdy73p3KcxV
// Component: BrV3uEHn-Yj
import * as React from "react";
import {
  hasVariant,
  createPlasmicElement,
  RenderOpts,
  Override,
  classNames,
  Flex,
  wrapWithClassName,
  Renderer,
  NodeRenderer,
  createPlasmicElementProxy,
  makeFragment,
  PlasmicIcon,
  PlasmicSlot,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss
import "./plasmic_copy_of_cloudflare_ip_checker.css"; // plasmic-import: pVt2oR5EtQUEdy73p3KcxV/projectcss
import "./PlasmicSpacer.css"; // plasmic-import: BrV3uEHn-Yj/css

export type PlasmicSpacer__VariantsArgs = {};

export type PlasmicSpacer__ArgsType = {};

const PlasmicSpacer__RenderFuncs = {
  spacer: (
    opts: RenderOpts<
      PlasmicSpacer__VariantsArgs,
      PlasmicSpacer__ArgsType,
      {
        spacer?: Flex<"div">;
      }
    >
  ): React.ReactElement => {
    const variants = opts.variants || {};
    const args = opts.args || {};
    const overrides = opts.overrides || {};
    return (
      <div
        data-plasmic-override={overrides.spacer}
        className={classNames({
          Spacer__spacer__CyK4Q: true,
          "plasmic-default__all": true,
          "plasmic-default__div": true
        })}
      ></div>
    );
  }
};

const PlasmicSpacer__FCs = {
  spacer: undefined
};

class PlasmicSpacer__Renderer extends Renderer<
  PlasmicSpacer__VariantsArgs,
  PlasmicSpacer__ArgsType,
  typeof PlasmicSpacer__RenderFuncs,
  "spacer"
> {
  constructor(
    variants: PlasmicSpacer__VariantsArgs,
    args: PlasmicSpacer__ArgsType
  ) {
    super(variants, args, PlasmicSpacer__RenderFuncs, "spacer");
  }

  protected create(
    variants: PlasmicSpacer__VariantsArgs,
    args: PlasmicSpacer__ArgsType
  ) {
    return new PlasmicSpacer__Renderer(variants, args);
  }

  withVariants(variants: PlasmicSpacer__VariantsArgs): PlasmicSpacer__Renderer {
    return super.withVariants(variants) as PlasmicSpacer__Renderer;
  }

  withArgs(args: PlasmicSpacer__ArgsType): PlasmicSpacer__Renderer {
    return super.withArgs(args) as PlasmicSpacer__Renderer;
  }

  getInternalVariantProps() {
    return [];
  }

  getInternalArgProps() {
    return [];
  }

  forNode(
    name: "spacer"
  ): NodeRenderer<typeof PlasmicSpacer__RenderFuncs["spacer"]>;
  forNode(name: keyof typeof PlasmicSpacer__RenderFuncs) {
    return super.forNode(name);
  }
}

interface PlasmicSpacerSpacerProps {
  variants?: PlasmicSpacer__VariantsArgs;
  args?: Partial<PlasmicSpacer__ArgsType>;
  spacer?: Flex<"div">;
}

export const PlasmicSpacer = ((props: PlasmicSpacerSpacerProps) => {
  return new PlasmicSpacer__Renderer(props.variants || {}, props.args || {})
    .forNode("spacer")
    .withOverrides({
      spacer: props.spacer
    })
    .render();
}) as React.FunctionComponent<PlasmicSpacerSpacerProps> & {
  createRenderer: () => PlasmicSpacer__Renderer;
};

PlasmicSpacer.createRenderer = () => new PlasmicSpacer__Renderer({}, {});

export default PlasmicSpacer;
/* prettier-ignore-end */
